services:
  blink-database:
    image: postgres:15.7-alpine3.19
    container_name: blink-database
    restart: on-failure
    networks:
      - blink
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blink
      POSTGRES_PASSWORD: blink
      POSTGRES_DB: blink
    volumes:
      - blink-database:/var/lib/postgresql/data

volumes:
  blink-database:
    driver: local

networks:
  blink:
    driver: bridge
