# Criar blink
POST http://localhost:3000/blinks
content-type: application/json

{
  "userId": "4bba3030-20e3-4780-b486-c7484b557fc8",
  "title": "Repositório",
  "url": "https://github.com/diego-aquino/blink-backend",
  "redirectId": "4dsglYo"
}

###

# Listar blinks
GET http://localhost:3000/blinks
  ?userId=4bba3030-20e3-4780-b486-c7484b557fc8
  &orderBy=title.desc
  &page=1
  &perPage=10

###

# Atualizar blink
PATCH http://localhost:3000/blinks/42ec7c40-ea39-4f3e-b152-c927e3f40167
content-type: application/json

{
  "userId": "4bba3030-20e3-4780-b486-c7484b557fc8",
  "title": "Repositório (atualizado)",
  "url": "https://github.com/diego-aquino/blink-frontend",
  "redirectId": "4dsglYo"
}

###

# Remover blink
DELETE http://localhost:3000/blinks/42ec7c40-ea39-4f3e-b152-c927e3f40167
content-type: application/json

{
  "userId": "4bba3030-20e3-4780-b486-c7484b557fc8"
}

###

# Acessar blink
GET http://localhost:3000/4dsglYo
